### ISSUE TITLE
VMMC Tab Missing Target 

### ISSUE THREAD

**Issue by CharlottePCOMOZ** [pepfar-datim/Beta-Pack-Feedback#10]
There does not seem to be an explicit VMMC target column in the VMMC Tab

**Comment by jacksonsj** [comment]
@WilliamShiflett - Could you add this into COP 19 repo with title: "Look into adding a cross-check coln in VMMC for total VMMC target"

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #243](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/243) via [**ZenHub**](https://www.zenhub.com/)
