### ISSUE TITLE
TX_TB_PREV

### ISSUE THREAD

**Issue by CharlottePCOMOZ** [pepfar-datim/Beta-Pack-Feedback#12]
The way column T is calculated, it assumes that all TB negative people who are currently on ART should get IPT every year of their lives, over and over again, as long as they don’t develop active TB.  This does not seem consistent with current clinical guidelines. 
Suggestion: There should be two assumptions for Targeted  % of patients to be placed on IPT (as opposed to Alternative TPT) 1 for New on ART and another for Already on ART

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #242](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/242) via [**ZenHub**](https://www.zenhub.com/)
