### ISSUE TITLE
HTS Tab calculations

### ISSUE THREAD

**Issue by CharlottePCOMOZ** [pepfar-datim/Beta-Pack-Feedback#13]
The way the HTS tab is programmed will require people to re-enter distributions every time the separately targeted modalities are updated (PMTCT, VMMC, index, and TB).  In the HTS tab, the calculations of numbers of positives needed are based on the product of total positives needed (column R) and the % of all positives from that modality (columns AB-AK).  This has the problem that you will have to update the % coming from each modality (columns AB-AK) every time the separately targeted modalities are updated (PMTCT, VMMC, index, and TB) so that the modalities all add up to 100%. 

 It would be better if the calculations were driven off of the Remaining HTS_TST_POS to identify (column Q) and the distributions (columns AB-AK) that are entered refer to the proportion of remaining modalities that come from each column.

**Comment by jacksonsj** [comment]
@CharlottePCOMOZ - Would it be helpful if the Other PITC column functioned as a "catch-all", with a function that fills in the difference between the sum of all other modalities and 100%?

This would only work if the sum of all other modalities is <100% (can't have negative shares in a modality to bring back down to 100%), but so long as you can get everything else down to under 100%, this would take care of the rest.

The other feature we're exploring is a table on the Summary tab where you could initially set modality shares by Prioritization type and Age/Sex (similar to TX_CURR growth rates), and then make finer changes in HTS tab later.

Would those two changes address the concern here?

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #240](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/240) via [**ZenHub**](https://www.zenhub.com/)

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #241](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/241) via [**ZenHub**](https://www.zenhub.com/)
