### ISSUE TITLE
TX <1 on TX Tab

### ISSUE THREAD

**Issue by CharlottePCOMOZ** [pepfar-datim/Beta-Pack-Feedback#14]
Please check infant portion of the formula for column in column M.  It looks like it’s calculating Tx_Curr for infants (age <1) as the sum of FY19 results * retention rate for already on ART + Tx_New *retention rate for new.  The problem with this is that the infants in the FY19 should not be included, because they will be age >=1 in COP19.  The Tx_Curr for infants < 1 should only include those newly diagnosed, i.e. $R*$O.

**Comment by jacksonsj** [comment]
@CharlottePCOMOZ - I know we discussed this on the Feedback Call today, but seemed like you had some concerns still. Could you add more here on what the link between EID and TX <1 does/doesn't look like in Mozambique for you all?

**Comment by CharlottePCOMOZ** [comment]
Hi,
My hesitation was because the EID data in Moz does not accurately reflect all <1s as it is only the first 9 months ( despite the definition being for 2-12 months) But I think it makes sense to calculate the >1 TX this way.
