### ISSUE TITLE
TX Suppression Rate Calculations on TX Tab

### ISSUE THREAD

**Issue by CharlottePCOMOZ** [pepfar-datim/Beta-Pack-Feedback#15]
In Column F you calculate the # of people with suppressed viral load through targeted testing.  Targeted testing is defined as “viral load tests ordered based on a specific clinical indication, (e.g., concern about disease progression or failure to respond to ART).”  In this calculation the same viral load suppression rate is used as for routine viral load testing. It does not make sense to expect the same viral suppression rate when the test is performed for concern about failure to respond to ART as for routine viral load testing. 
Suggestion: Column AD (VL suppression rate) be divided into one column for Routine VL suppression rate and another for Targeted VL suppression rate.

**Comment by pvinayak001** [comment]
KFC: We are not targeting for targeted. All PVLS targets should be in routine. 
95% of those on treatment should be suppressed.

**Comment by jacksonsj** [comment]
This has been added to COP19 Repo for development
