### ISSUE TITLE
Prioritizations

### ISSUE THREAD

**Issue by HosseiniPR** [pepfar-datim/Beta-Pack-Feedback#16]
The drop down menu of the prioritizations only has a limited set of possible options:
![image](https://user-images.githubusercontent.com/20465203/50168922-7f094f80-02ba-11e9-9f57-5bdc8f3ecb96.png)

From draft COP19 guidance, there are more prioritizations:
![image](https://user-images.githubusercontent.com/20465203/50169362-71a09500-02bb-11e9-8abc-ec2dcc71504c.png)

And here are the DATIM codes: https://datim.zendesk.com/hc/en-us/articles/208663096-FY2017-Planning-and-Implementation-Attributes

-Parviez

**Comment by jacksonsj** [comment]
This has been added to COP19 Repo for incorporation into Data Pack
