### ISSUE TITLE
Question: The space to the right?

### ISSUE THREAD

**Issue by HosseiniPR** [pepfar-datim/Beta-Pack-Feedback#17]
This is more a guidance question -- but the columns to the right of the pre-populated/structured columns -- can this be used as a scratch pad, or for country specific custom calculations?  For example, on the PP tab,  could you use columns L through ZZ to calculate targets in a custom way?

What are up/downsides (size, messing with site-level tool)?  If can't be used, we need to make that clear. Or if it has to be clear before submission or something (i.e., paste special values, etc).

**Comment by jacksonsj** [comment]
@HosseiniPR - Generally, yes you can use blank space to add data/calculations. You can also add columns in the middle of data entry tables as well. Nothing in the Data Pack prevents that.

Your last question I think is the real determinant. My initial response is definitely no on leaving custom columns in the middle of entry tables and _probably_ no on leaving them in blank space, but I'll play with that and make sure.

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #239](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/239) via [**ZenHub**](https://www.zenhub.com/)
