### ISSUE TITLE
Zimbabwe Comments on datapack 

### ISSUE THREAD

**Issue by PCOZim** [pepfar-datim/Beta-Pack-Feedback#18]
[Comments on the Data pack.docx](https://github.com/pepfar-datim/Beta-Pack-Feedback/files/2693544/Comments.on.the.Data.pack.docx)

**Comment by jacksonsj** [comment]
@WilliamShiflett - Could you help me put these into separate tickets in this feedback repo?

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #238](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/238) via [**ZenHub**](https://www.zenhub.com/)
