### ISSUE TITLE
OVC datapack issues 

### ISSUE THREAD

**Issue by PCOZim** [pepfar-datim/Beta-Pack-Feedback#19]
1.	For OVC_SERV, having targeted graduation rates by sex and age may not work.
2.	For OVC_HIVSTAT, there is no need of setting absolute targets since the denominator of this indicator is informed by OVC_SERV <18 Achieved. I would recommend removing Column 'O'.

**Comment by jacksonsj** [comment]
@WilliamShiflett - Could you add the OVC_HIVSTAT issed and the OVC_SERV issue as two separate tickets in the COP19 repo and tag for `Kristine/Ebonnie`? Assign to me.

**Comment by erinschelar** [comment]
For OVC_HIVSTAT, recommend not setting targets as it does not make sense to look at achievement against these targets.

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #237](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/237) via [**ZenHub**](https://www.zenhub.com/)
