### ISSUE TITLE
OVC Served

### ISSUE THREAD

**Issue by annieschwartz** [pepfar-datim/Beta-Pack-Feedback#22]
The OVC tab has some errors – the comment should say Numerator, not Denominator (or just remove it that entirely). 
![image](https://user-images.githubusercontent.com/36447976/50230181-2dc09500-037a-11e9-916c-c7273112dc35.png)

**Comment by erinschelar** [comment]
How is the targeted % graduation rate populated? From programmatic perspective, do not recommend including more than 10% graduated as a baseline number. MER v2.3 changes added graduation benchmarks which are a high standard and make it unlikely that large proportions should be graduating.

**Comment by erinschelar** [comment]
Targets should be set only for 18+, not 18-24 and 25+ as in MER v2.3 the age categories are combined

**Comment by jacksonsj** [comment]
This has been added to COP19 Repo for development.

Thank you @erinschelar and @annieschwartz !
