### ISSUE TITLE
TX: National ART coverage (FY20)

### ISSUE THREAD

**Issue by annieschwartz** [pepfar-datim/Beta-Pack-Feedback#25]
Check formula for targeted national ART coverage (FY20). The values I get do not calculate to >5000%

![image](https://user-images.githubusercontent.com/36447976/50230693-29e14280-037b-11e9-83eb-7be0960fe203.png)

**Comment by jacksonsj** [comment]
@annieschwartz - Could you give me a specific example of what this value should be compared with what the current formula gives?

This should forecast, not what the actual estimated ART coverage is as reported from Spectrum, but what the coverage would be if PEPFAR's TX_CURR (FY20) were according to col M, and that represented X proportion of the total National ART, with X given in column L. The denominator, then, would be PLHIV coming from Spectrum's estimates.

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #232](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/232) via [**ZenHub**](https://www.zenhub.com/)

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #234](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/234) via [**ZenHub**](https://www.zenhub.com/)
