### ISSUE TITLE
Prevention Indicators in Moz DP

### ISSUE THREAD

**Issue by CharlottePCOMOZ** [pepfar-datim/Beta-Pack-Feedback#8]
KP Tab
No prepopulated data for KP_PREV
Moz has no historical data for KP disaggregates in other indicators as reporting is optional

PREP Tab
No Data included in FY19 Expected Results

PP Tab
AGYW_PREV - not included?

GEND Tab
 Data in FY19 Expected results do not match FY18 results or FY19 targets.

**Comment by jacksonsj** [comment]
@CharlottePCOMOZ - Answers below, summarized from Feedback Call this morning.

KP Tab
No prepopulated data for KP_PREV
`Final Data Pack will include FY19 Target data for KP indicators, where this is available from DATIM`
Moz has no historical data for KP disaggregates in other indicators as reporting is optional
`Reporting on these indicators in Data Pack is also optional`

PREP Tab
No Data included in FY19 Expected Results
`Where this data exists in DATIM, the final Data Pack will include FY19 Targets in the PrEP tabs, but specific guidance from Irum was to not include any formulas to aid in setting targets for PrEP. I know USAID and CDC SI leads have been exploring a specific tool to help with this, but do not know current status.`

PP Tab
AGYW_PREV - not included?
`Not required for targets, but will be for results.`

GEND Tab
Data in FY19 Expected results do not match FY18 results or FY19 targets.
`Will look into this issue RE: the _unallocated districts. Are there other cases where this is affected targets?`

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #244](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/244) via [**ZenHub**](https://www.zenhub.com/)
