### ISSUE TITLE
_unallocated districts in Moz DP

### ISSUE THREAD

**Issue by CharlottePCOMOZ** [pepfar-datim/Beta-Pack-Feedback#9]
There should be no data in unallocated districts in any indicator

**Comment by jacksonsj** [comment]
@WilliamShiflett - Could you add this to the COP 19 repo and assign to @sam-bao ?

**Comment by jason-p-pickering** [comment]
I am not sure what the suggestion of how to handle this may be, but there is data in DATIM for some indicators for a district labeled _xai_xai_unallocated. See attached. 

![image](https://user-images.githubusercontent.com/2968061/50225937-30cf7b80-03a2-11e9-8bb0-f378cb7a2094.png)
